//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPgpA001 {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppPgpA001.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Basis ähnelt.
        /// </summary>
        internal static string Basis {
            get {
                return ResourceManager.GetString("Basis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create stereo pair ähnelt.
        /// </summary>
        internal static string CreateStereoPair {
            get {
                return ResourceManager.GetString("CreateStereoPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display left image points ähnelt.
        /// </summary>
        internal static string DisplayLeftImagePoints {
            get {
                return ResourceManager.GetString("DisplayLeftImagePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display right image points ähnelt.
        /// </summary>
        internal static string DisplayRightImagePoints {
            get {
                return ResourceManager.GetString("DisplayRightImagePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OpenCV Tests ähnelt.
        /// </summary>
        internal static string FormMainTitle {
            get {
                return ResourceManager.GetString("FormMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left image RESET ZOOM ähnelt.
        /// </summary>
        internal static string LeftImageResetZoom {
            get {
                return ResourceManager.GetString("LeftImageResetZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left image zoom IN ähnelt.
        /// </summary>
        internal static string LeftImageZoomIn {
            get {
                return ResourceManager.GetString("LeftImageZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left image zoom OUT ähnelt.
        /// </summary>
        internal static string LeftImageZoomOut {
            get {
                return ResourceManager.GetString("LeftImageZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load left image ähnelt.
        /// </summary>
        internal static string LoadLeftImage {
            get {
                return ResourceManager.GetString("LoadLeftImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load right image ähnelt.
        /// </summary>
        internal static string LoadRightImage {
            get {
                return ResourceManager.GetString("LoadRightImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load selected points of left image ähnelt.
        /// </summary>
        internal static string LoadSelectedPointsLeftImage {
            get {
                return ResourceManager.GetString("LoadSelectedPointsLeftImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load selected points of right image ähnelt.
        /// </summary>
        internal static string LoadSelectedPointsRightImage {
            get {
                return ResourceManager.GetString("LoadSelectedPointsRightImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load stereo pair ähnelt.
        /// </summary>
        internal static string LoadStereoPair {
            get {
                return ResourceManager.GetString("LoadStereoPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pan left image ähnelt.
        /// </summary>
        internal static string PanLeftImage {
            get {
                return ResourceManager.GetString("PanLeftImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pan rigt image ähnelt.
        /// </summary>
        internal static string PanRightImage {
            get {
                return ResourceManager.GetString("PanRightImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Proc stereo pair ähnelt.
        /// </summary>
        internal static string ProcStereoPair {
            get {
                return ResourceManager.GetString("ProcStereoPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right image RESET ZOOM ähnelt.
        /// </summary>
        internal static string RightImageResetZoom {
            get {
                return ResourceManager.GetString("RightImageResetZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right image zoom IN ähnelt.
        /// </summary>
        internal static string RightImageZoomIn {
            get {
                return ResourceManager.GetString("RightImageZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right image zoom OUT ähnelt.
        /// </summary>
        internal static string RightImageZoomOut {
            get {
                return ResourceManager.GetString("RightImageZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save selected points of left image ähnelt.
        /// </summary>
        internal static string SaveSelectedPointsLeftImage {
            get {
                return ResourceManager.GetString("SaveSelectedPointsLeftImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save selected points of right image ähnelt.
        /// </summary>
        internal static string SaveSelectedPointsRightImage {
            get {
                return ResourceManager.GetString("SaveSelectedPointsRightImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save stereo pair ähnelt.
        /// </summary>
        internal static string SaveStereoPair {
            get {
                return ResourceManager.GetString("SaveStereoPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stereo pair info ähnelt.
        /// </summary>
        internal static string StereoPairInfo {
            get {
                return ResourceManager.GetString("StereoPairInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stereo pair settings ähnelt.
        /// </summary>
        internal static string StereoPairSettings {
            get {
                return ResourceManager.GetString("StereoPairSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Synchronize by left image ähnelt.
        /// </summary>
        internal static string SyncByLeftImage {
            get {
                return ResourceManager.GetString("SyncByLeftImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Synchronize by right image ähnelt.
        /// </summary>
        internal static string SyncByRightImage {
            get {
                return ResourceManager.GetString("SyncByRightImage", resourceCulture);
            }
        }
    }
}
